file(GLOB_RECURSE files RELATIVE "${SOURCE}" "${SOURCE}/*")
foreach(file IN LISTS files)
    if(file MATCHES "TF2VRBetterBindings\\.ini$" AND EXISTS "${DESTINATION}/${file}")
        message(STATUS "keeping existing ${file}")
        continue()
    endif()
    get_filename_component(directory "${DESTINATION}/${file}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    file(COPY_FILE "${SOURCE}/${file}" "${DESTINATION}/${file}")
endforeach()
message(STATUS "installed into ${DESTINATION}")
